### PR TITLE
Added GraphQL integration.

### PR DESCRIPTION
**Pull request by radekmie**
Finally, I've come up with an API idea on _how_ to integrate SparrowQL with GraphQL.

Long story short: there's a new `buildFromGraphQL(info, options)` function, that makes use of GraphQL `info` object. Options are the standard options, with two exceptions: one, `projection` is ignored, as it's build from the query, two, there's a new `typeMap: {[string]: string}`, which maps a field to a collection.

Demo and tests are in [`__tests__/demo-graphql.js`](https://github.com/vazco/sparrowql/blob/a55a51bff81f556df78c5c7ab0f0cabf229e6a26/__tests__/demo-graphql.js).

As I'm not sure about two things, and I'd love some feedback:
* Is the `typeMap` actually clear and named correctly? Maybe we could extract it from the schema, but I don't have any idea on how to define it in there in a convinient way.
* It introduces a dependency, but it's not marked in the `dependencies`, as it's _optional_ (as long as you are not using this function). I'd use `peerDependencies`, but it's still results in a warning. Maybe we should release a new package (but it's only a single function!)?

---

Background:
Same as the whole SparrowQL, the idea of integrating it with GraphQL popped out in an internal hackathon. We've done _something_, but the results were... Bad? Mostly, because you had to define the whole relations and mappings in your schema. It looked like this:

```graphql
type Customer @db(name: customers) {
  _id: ID!
  restaurants: [Restaurant!]! @relation(field: restaurantIds)
  restaurantIds: [ID!]!
  reservations: [Reservation!]! @reversedRelation(field: customerId)
}
```

It was definitely too verbose. After some time, and giving it some thoughts I have a new API idea. In short, we keep your schema as it is, but instead, we do parse the query and build a `projection` from it. The only _problem_ at the moment is that we don't track the types, so you have to provie the `typeMap`.

Also, thanks to @janowsiany, as he is the reason, why I didn't included the whole GraphQL integration in the first release, as it was _not so GraphQL_. :rocket:

### CODE REVIEW

**Review by MacRusher — APPROVED** [review]

**Comment by janowsiany** [comment]
Definitely looks more _GraphQL_ alike. Great job 🥇
Only thing which bothers me is that the pipeline in the demo is recalculated with each resolver call.

Also i think that the possibility to define your options with schema should not be removed. I think that with following schema one could build the options you defined in test cases or i miss something?
```graphql
type Blog @collection(name: "blogs") {
  _id: ID!
  owner: User! @relationTo(foreignField: "_id")
  topic: String!
}

type Post @collection(name: "posts") {
  _id: ID!
  author: User! @relationTo(foreignField: "_id")
  blog: Blog! @relationTo(foreignField: "_id")
  title: String!
}

type User @collection(name: "users") {
  _id: ID!
  about: String!
  name: String!
}

type Query {
  posts: [Post!]!
}
```
I find this way of doing that much more declarative.

**Comment by radekmie** [comment]
> Only thing which bothers me is that the pipeline in the demo is recalculated with each resolver call.

It has to, as the pipeline depends on the query (selection set to be exact).

> Also i think that the possibility to define your options with schema should not be removed. I think that with following schema one could build the options you defined in test cases or i miss something?

I'm still thinking about it, but without a result (yet). The problem is, that you'd have to define, which alias of `User` (let's stick to this example) you join. As in #1, you can't join a single collection twice. What is more, in GraphQL you'd rather define `blog` than `blogId`, but there's no `blog` in the DB. In this case, it _could_ look something like this:

```graphql
type Blog @collection(name: "Blogs") {
  _id: ID!
  owner: User! @relationTo(localField: "ownerId", foreignField: "_id", as: "Owners")
  topic: String!
}

type Post @collection(name: "Posts") {
  _id: ID!
  author: User! @relationTo(localField: "authorId", foreignField: "_id", as: "Authors")
  # `as` defaults to collection name
  blog: Blog! @relationTo(localField: "blogId", foreignField: "_id")
  title: String!
}

type User @collection(name: "Users") {
  _id: ID!
  about: String!
  name: String!
}

type Query {
  posts: [Post!]!
}
```

Now, we have everything we need, but we've mixed concerns, because our schema know about the DB structure (it's not _that_ bad, but still).

**Comment by radekmie** [comment]
I've made something, that works with the above directives (I'll share later as I'll test it a bit more). What do you think?

**Comment by MacRusher** [comment]
Great solution, very nice job! :tada: I can already see very useful use-cases for this.

> Is the `typeMap` actually clear and named correctly?

IMHO `typeMap` is an acceptable approach, it would be probably defined once per project anyway and passed through context. I'll also see usage for an higher-order function that is "ready to use" in resolvers, but this probably should be project-specific, e.g.:
```javascript
import {buildFromGraphQL} from 'sparrowql';

// Once per project
const aliases = {};
const typeMap = {};
const relations = {};

// Probably passed trough context
const buildPipeline = (info, params = {}) => buildFromGraphQL(info, {aliases, typeMap, relations, ...params});

const resolver = {
  posts(args, context, info) {
    const pipeline = buildPipeline(info, {start: 'Posts'});
    return Posts.aggregate(pipeline).toArray();
  }
};
```

> Maybe we should release a new package (but it's only a single function!)?

I think that a new package working as a GraphQL extension to SparrowQL is the best approach in the long run, but this would probably require to set up a monorepo, and I'm not sure if this is worth the burden at this point.

> Now, we have everything we need, but we've mixed concerns, because our schema know about the DB structure (it's not that bad, but still).

I'm personally against leaking any implementation-specific data to the schema, including collection and fields names. This will also make schema much less readable, with lots of repetitions, especially if one wants to use SparrowQL only in few resolvers.

Keeping a separate "schema" in the form of `aliases`, `typeMap` and `relations` seems lesser evil to me.

Of course, there is a place for an opt-in approach.

**Comment by radekmie** [comment]
Yep, opt-in. In practice, there will be a function `f: schema -> options`, but you'll be able to write the options by hand.

I'm for monorepo too - it's not that hard with Lerna. After that, I'll update this PR with further implementation.

**Comment by radekmie** [comment]
OK, I've rebased and implemented the schema integration. Here's a short summary with a working example:

```graphql
directive @collection(name: String!) on OBJECT
directive @relationTo(local: String!, foreign: String!, as: String) on FIELD_DEFINITION

type Blog @collection(name: "Blogs") {
  _id: ID!
  owner: User! @relationTo(local: "ownerId", foreign: "_id", as: "Owners")
  topic: String!
}

type Post @collection(name: "Posts") {
  _id: ID!
  author: User! @relationTo(local: "authorId", foreign: "_id", as: "Authors")
  # "as" defaults to collection name
  blog: Blog! @relationTo(local: "blogId", foreign: "_id")
  title: String!
}

type User @collection(name: "Users") {
  _id: ID!
  about: String!
  name: String!
}

type Query {
  posts: [Post!]!
}
```

```js
import {astToOptions, astToPipeline} from 'sparrowql-graphql';

const options = astToOptions(parse(schema));

options === {
  collections: ['Blogs', 'Posts', 'Users'],
  relations: [
    {foreign: '_id', from: 'Blogs', local: 'ownerId', to: 'Owners'},
    {foreign: '_id', from: 'Posts', local: 'authorId', to: 'Authors'},
    {foreign: '_id', from: 'Posts', local: 'blogId', to: 'Blogs'}
  ],
  typeMap: {
    'Blog.owner': 'Owners',
    'Post.author': 'Authors',
    'Post.blog': 'Blogs',
    'Query.posts': 'Posts'
  }
};

// Then...
const resolver = {
  posts(args, context, info) {
    const pipeline = astToPipeline(info, {
      ...options,
      aliases: {
        Authors: Users.collectionName,
        Blogs: Blogs.collectionName,
        Posts: Posts.collectionName,
        Owners: Users.collectionName
      },
      start: 'Posts'
    });

    return Posts.aggregate(pipeline).toArray();
  }
};
```

So, there is a new package: `sparrowql-graphql`, with two new functions: `astToOptions` and `astToPipeline`. First one is completely optional, as you can write these options by hand, to partially enable or disable certain relations. Second one is the _core_ one.

Actually, `astToOptions` returns more than it's needed (`collections` is not needed), but it _might_ be needed in the future (for new features) and it's easy to get it, so it's there. Notice that `typeMap` has changed a bit: it's really important, as field name is not enough (and types are distinct, so it's OK).

When it comes to directives and collisions: we've got you covered:

```js
astToOptions(schemaAST, {
    directiveCollection: 'sparrowCollection',
    directiveRelation: 'sparrowRelationTo'
});
```

Note, that it also mean, that you have to define them (as in the example above)!

Problems? Few:

* Error handling is... Non existing at the moment.
* `Query` type has to be the last one (implementation detail, but I'd rather won't pass the schema twice).
* `start` makes less and less sense... I have an idea to make it optional. That's where `collections` come handy: we can _try_ each one and pick the _best_: less `$lookup` is better.

**Pull request merged**
